import { useState } from "react";
import { useLoaderData, useRevalidator } from "react-router";
import { useAppBridge } from "@shopify/app-bridge-react";
import { boundary } from "@shopify/shopify-app-react-router/server";
import { authenticate } from "../shopify.server";
import db from "../db.server";
import { authenticatedPost } from "../lib/authenticated-post";
import { AUTOMATION_CHANNELS, normalizeEventKey } from "../lib/automations";

export const loader=async({request})=>{const{session}=await authenticate.admin(request);const events=await db.submissionEvent.findMany({where:{release:{shop:session.shop}},orderBy:{createdAt:"desc"},take:100,include:{release:{select:{id:true,title:true,type:true,ownerCustomerId:true}},deliveries:true}});return{events};};
const channelLabel=(c)=>({ARTIST_EMAIL:"Artist email",ADMIN_EMAIL:"Admin email",SHOPIFY_FLOW:"Shopify Flow"}[c]||c);
export default function Notifications(){const{events}=useLoaderData(),shopify=useAppBridge(),revalidator=useRevalidator();const[busy,setBusy]=useState(null),[notice,setNotice]=useState(null);const retry=async(eventId,channel)=>{const key=`${eventId}:${channel}`;setBusy(key);setNotice(null);try{const f=new FormData();f.set("eventId",eventId);f.set("channel",channel);const r=await authenticatedPost(shopify,"/api/notifications",f);setNotice({tone:"good",message:r.message});await revalidator.revalidate();}catch(e){setNotice({tone:"bad",message:e.message})}finally{setBusy(null)}};return <s-page heading="Notifications"><s-section><div style={styles.hero}><div style={styles.eyebrow}>Delivery log</div><div style={styles.title}>Release events & automation delivery</div><div style={styles.copy}>See which artist emails, internal emails, and Flow triggers were sent. Retry an individual channel without replaying the release workflow.</div></div></s-section>{notice?<s-section><div style={styles.notice}>{notice.message}</div></s-section>:null}<s-section><div style={styles.list}>{events.length?events.map(event=><article key={event.id} style={styles.event}><div style={styles.eventHead}><div><strong>{event.release.title}</strong><div style={styles.meta}>{normalizeEventKey(event.type)} · {new Date(event.createdAt).toLocaleString()}</div></div><div style={styles.meta}>{event.actorLabel||"ReleaseCore"}</div></div>{event.message?<div style={styles.message}>{event.message}</div>:null}<div style={styles.deliveryGrid}>{Object.values(AUTOMATION_CHANNELS).map(channel=>{const d=event.deliveries.find(x=>x.channel===channel);return <div key={channel} style={styles.delivery}><div><strong>{channelLabel(channel)}</strong><div style={styles.meta}>{d?`${d.status} · ${d.attempts} attempt${d.attempts===1?"":"s"}`:"Not triggered"}</div>{d?.lastError?<div style={styles.error}>{d.lastError}</div>:null}</div><button type="button" style={styles.button} disabled={busy===`${event.id}:${channel}`} onClick={()=>retry(event.id,channel)}>{d?.status==="SENT"?"Send again":"Retry"}</button></div>})}</div></article>):<div style={styles.empty}>No release events yet.</div>}</div></s-section></s-page>}
export const headers=(args)=>boundary.headers(args);
const styles={hero:{padding:"20px 2px"},eyebrow:{fontSize:12,fontWeight:750,letterSpacing:".08em",textTransform:"uppercase",color:"#6d7175"},title:{fontSize:28,fontWeight:750,marginTop:6},copy:{color:"#6d7175",maxWidth:760,marginTop:6},list:{display:"grid",gap:12},event:{padding:15,border:"1px solid #dedede",borderRadius:12},eventHead:{display:"flex",justifyContent:"space-between",gap:12},message:{fontSize:13,marginTop:10,color:"#444"},deliveryGrid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:8,marginTop:14},delivery:{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",padding:10,border:"1px solid #eee",borderRadius:9,background:"#fafafa"},meta:{fontSize:12,color:"#6d7175",marginTop:3},error:{fontSize:11,color:"#a21b12",marginTop:4,maxWidth:300},button:{border:"1px solid #c9cccf",borderRadius:7,background:"#fff",padding:"7px 10px",fontWeight:600},notice:{padding:12,border:"1px solid #dedede",borderRadius:9},empty:{padding:18,color:"#6d7175"}};
